[bastion]
bastion ansible_host=REPLACE_WITH_BASTION_PUBLIC_IP ansible_user=ec2-user

[vps]
vps ansible_host=14.225.208.14 ansible_user=root

[worker]
# worker (formerly local)
worker ansible_host=10.10.0.2 ansible_user=root
